// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhsjhoygllcchfinalih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoc2pob3lnbGxjY2hmaW5hbGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjE4MzcsImV4cCI6MjA2MzU5NzgzN30.2TEzTNMYMcVuBoC9t1zdkjZ66FosDzO-byE6WylI9Gg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);